CREATE TABLE employe(
id BIGINT( 100 ) NOT NULL AUTO_INCREMENT ,
name VARCHAR( 20 ) NOT NULL ,
pass VARCHAR(30) NOT NULL,
email VARCHAR( 50 ) NOT NULL ,
pic TEXT NOT NULL ,
PRIMARY KEY ( id )
) ENGINE = INNODB